apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minecraft

resources:
  - namespace.yaml
  - dns-endpoint.yaml
  - postgres/
  - velocity/
  - fabric/
  - admin/

commonLabels:
  app.kubernetes.io/part-of: minecraft-realm
