apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minecraft

resources:
  - namespace.yaml
  - postgres/
  - velocity/
  - fabric/
  # - admin/  # TODO: Enable when ready

commonLabels:
  app.kubernetes.io/part-of: minecraft-realm
