apiVersion: v1
kind: Secret
metadata:
    name: rcon-credentials
    namespace: minecraft
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:WAz66is=,iv:vP7DMGo+9+ZOrgKFB1YtBeQssQXtUpB83rp4T7a2dhw=,tag:oYmNy65QLYC1fJrprIhLQg==,type:str]
    password: ENC[AES256_GCM,data:7UPyFFiGuiOWuOxxCbLgfp4O34KLCjLORiBuOtu7hDg=,iv:llFQPx+FK3yUq7R1Eiew+9IufTRi0LEBpr/kF7onJlw=,tag:ii7Qfj27986+8p3SeuZG7w==,type:str]
    rcon-password: ENC[AES256_GCM,data:X/VdwUDSI0GbBSQfnCTHKVQKgZHou248HncC5HWuEGU=,iv:OJMUdFL0I/UBnq756xdl03pxXjp1Qu/+tTOI2OjB8E0=,tag:KhWyWedfB8KkDWwdytX3xA==,type:str]
sops:
    age:
        - recipient: age1zxja08zu7wkczkvwfek2r8zj6hdq0d5rx46f8v8lzajwhjr3499sanxzyc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVY3hab09qSHVqTm9iTGlk
            QmVieEpvNWttSitTbGJVOGpIcmU4S0R2aUQwCkJZM3hid3E0K2JXMTVTSU9OZGlu
            UFcyYVB6aHZEUFJOL3NiVXJvZmh0VnMKLS0tIGZtaDI4QzFHa2ZnL255ZytMUWNm
            U0xPN3U3a1o2YlNMbHFNVTRlMG5KNkkK+fOAJu9HMPkiktPHoutVHyChQpoa0DYz
            wGl9C36W8pAdkr9JidIaxoaqG8fibqFW5GnjrJokHml9rZE0ZMHdgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T23:52:01Z"
    mac: ENC[AES256_GCM,data:rw/nRh+AW5N//wo00eMfnclpd+LTL/WN/dgKLX5Ar1F07PcPYKIMEahPkc5nI3mlMyrfxfH3G6zbb2SxNnJTHCYk8usbsHhfsItVO4Jofev/zP9f+TvJubCbJuFFgTSI0o4FWfol5ixuyubNOq8KQ8HkyxTsNFTJXSknfEZ1BsM=,iv:DWHhkeHed8yACezsoN5oxmqbGmuBrmrAil5fqrw5ssg=,tag:vsoCTTqyVYdYefReLM9SBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
