apiVersion: v1
kind: Secret
metadata:
    name: minecraft-postgres-credentials
    namespace: minecraft
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:4R8h12DVu3K2,iv:blYZ4sCx+CRTS1GBiWryu6lOgnL2EgJefjtiWfdw6yA=,tag:tAZYR2CwQ9m0BXBnKSPEaA==,type:str]
    password: ENC[AES256_GCM,data:fRWGQc/YRSdE8kGOEcrgSPgnd09k4KhTLcx4lBxMcAs=,iv:R40jidVotuEAe+vWN7LSJa/XDi9t6WUNBWz2AbUFyuE=,tag:ik9uKQZgiRqGSSkIykYPkQ==,type:str]
sops:
    age:
        - recipient: age1zxja08zu7wkczkvwfek2r8zj6hdq0d5rx46f8v8lzajwhjr3499sanxzyc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUUR2aW43NXlWeVl2MG1z
            blNzWmJWMk1WTnFid2MwbGpMdjdRSVY2dXlZCnpJMS9FczNmdGNUTS9TWit6Ukpi
            SXNHMXlpYXR2cnJWZmFNaWtiRGU1VzgKLS0tIFBaY0NNNmJKWU1JeUh5K1A3RFRq
            MlA4Y3MzZVlYdWtNTTBFSzd1SlVGazgKEXF2ShhII4TqKtKTa+arcja2EmCSHh4S
            CGsbJIeHNHVzoTbpzx/GibSC13jnSVHKmzxCBqGgttAl3EclzxVO6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T23:11:10Z"
    mac: ENC[AES256_GCM,data:YnFYdb2B1sqOc9Up9d7IhD42yaJtq3oEm8D4ljgQD2F83nIgBbA7PqvEufntu0FT9Xo95DR4BSE3DjlaT4Hib5bDbfQcPMz1PmCZX7Vl6JZTVOjd+QCfs48GETuSRqCK71FPJsfZ3b8i8Lb12BHy7vy3YZdYSXjDD0UJ5BQJPuQ=,iv:f/r6EA6R6WkfU5zIkyITR2KGkuiCs14CR6ww5/kEYno=,tag:NYwahHCSzMpbUkzNSFHXHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
