apiVersion: v1
kind: Secret
metadata:
    name: velocity-forwarding
    namespace: minecraft
type: Opaque
stringData:
    forwarding.secret: ENC[AES256_GCM,data:oPH5bo4JXhcEiuZBqux7WA2KU4VQ7QH8jZmionBtyyEfa3r/L4OFx3pneH8o/X3m/MURZdcn08LAIsGrxlqTnw==,iv:kZhrn+6tZrU2CGXWp11zarLH6uvplWDhYK904Bq6y+Q=,tag:ZnerVQxEDzDXJg3vLPqDbw==,type:str]
sops:
    age:
        - recipient: age1zxja08zu7wkczkvwfek2r8zj6hdq0d5rx46f8v8lzajwhjr3499sanxzyc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Q0xkVDNCSGJBWm5EeFlx
            MVV5ZVN1S0JiL0JVZElkMjBuclljSnFSNDEwCmp2Vm9PV0pJRklpVmJQY1VZOWdh
            YWhsOXUvK1BmWE5sUVd3MlRuVThzdGMKLS0tIGxZVW5lWTFIYjdST09MUlNySzBn
            Qmd2Y3crQUFlSStaV0swNHFSNlBucmMKgv+hRY3/hVEOXo+6MrKItePnZro7QJxk
            rEyLX2cmBho1fRe31v0MJ/ai3GwCeekwgoYA2sffzyq7faMbf+4bjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T23:11:10Z"
    mac: ENC[AES256_GCM,data:lkMxuIJERHupb10M/nRgTC6n4mQ4VVoKxLO1+NBzWb4FccifXNTDdUaxC6++Q39yvKL6GWEkf9XudfTOTdYtES3QObfa2B58hOUAg9PaLMNYbU698WHqcjHuJfjrLSKI5Xyi/97CJnibA1GLlHBfjJ+ywN0+YBl77I0ZPkEeG2Q=,iv:GvwLbm/bBu2R19oFkRtV1BCwfKrRxoNTHmihwI1xoTs=,tag:oJ+2eZb6lav1LNgrv/UKcw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
