apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service-tcp.yaml
  - service-udp.yaml
  - udp-forwarder.yaml
  - configmap.yaml
  - forwarding.secret.enc.yaml
