apiVersion: v1
kind: Service
metadata:
  name: velocity-tcp
  namespace: minecraft
  labels:
    app: velocity-proxy
spec:
  type: ClusterIP
  selector:
    app: velocity-proxy
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
      name: java
