apiVersion: v1
kind: Service
metadata:
  name: velocity-bedrock
  namespace: minecraft
  labels:
    app: velocity-proxy
  annotations:
    # External DNS will create DNS record automatically
    external-dns.alpha.kubernetes.io/hostname: minecraft.bentleyalberta.com
spec:
  type: LoadBalancer
  selector:
    app: velocity-proxy
  ports:
    - port: 19132
      targetPort: 19132
      protocol: UDP
      name: bedrock
